# Video Content System Configuration

# Whisper設定
whisper:
  model: base              # tiny, base, small, medium, large
  language: ja             # 日本語
  device: cpu              # cpu or cuda
  verbose: false           # 詳細ログ
  
# 出力設定
output:
  base_dir: ./output
  jekyll_posts_dir: ./_posts
  keep_temp_files: false
  
# Jekyll設定
jekyll:
  layout: post
  categories:
    - video
    - blog
  author: "Video Bot"
  permalink_format: "/:year/:month/:day/:title/"
  
# コンテンツ生成設定
content:
  # ブログ記事
  blog:
    optimize_content: true     # BlogOptimizerを使用（デフォルト）
    target_quality: high       # 高品質なコンテンツ生成
    output_format: html        # HTML形式で出力（ブログ向け）
    natural_japanese: true     # 自然な日本語に変換
    min_section_length: 200    # セクション最小文字数
    max_section_length: 500    # セクション最大文字数
    add_timestamps: true       # タイムスタンプ追加
    add_toc: true             # 目次追加
    generate_images: true      # 画像自動生成を有効化
    generate_featured_image: true  # アイキャッチ画像生成
    generate_section_images: true  # セクション画像生成
    image_settings:
      primary_color: "#2c3e50"
      secondary_color: "#3498db"
      accent_color: "#e74c3c"
      text_color: "#ffffff"
      background_color: "#1a1a2e"
    
  # YouTube
  youtube:
    add_chapters: true         # チャプター追加
    max_description_length: 5000
    default_tags:
      - 動画
      - ブログ
      - 日本語
    
  # X (Twitter)
  twitter:
    max_length: 140
    add_hashtags: true
    max_hashtags: 3
    
# サムネイル設定
thumbnail:
  width: 1280
  height: 720
  background_color: "#1a1a2e"
  text_color: "#ffffff"
  accent_color: "#f39c12"
  font_size_title: 80
  font_size_subtitle: 40
  
  # 画像生成プロバイダー設定（画像タイプ別）
  image_providers:
    youtube_thumbnails: "dalle3"    # サムネイル: DALL-E 3（高品質・日本語対応）
    blog_featured: "dalle3"         # ブログアイキャッチ: DALL-E 3（高品質）
    blog_sections: "dalle2"         # ブログセクション画像: DALL-E 2（コスト効率）
  
  # DALL-E 3設定（サムネイル・アイキャッチ用）
  dalle3:
    api_key: ""  # OpenAI APIキーをユーザーが設定
    default_size: "1792x1024"    # YouTube用最適サイズ
    quality: "hd"                # standard または hd
    style: "natural"             # natural または vivid
    
    # 生成戦略
    strategies:
      youtube_impact: "インパクト型"     # 大きなテキスト、強いビジュアル
      youtube_curiosity: "好奇心型"      # 疑問符、ミステリアス
      youtube_authority: "権威型"       # プロフェッショナル、信頼感
  
  # DALL-E 2設定（ブログセクション画像用 - コスト効率）
  dalle2:
    api_key: ""  # OpenAI APIキー（DALL-E 3と同じ）
    default_size: "1024x1024"    # 正方形（ブログ用）
    
    # コスト効率設定
    cost_per_image: 0.020        # $0.02/image (DALL-E 2)
    vs_dalle3_savings: "75%"     # DALL-E 3比75%コスト削減
  
  # Runware API設定（フォールバック - 高速・低コスト）
  runware:
    api_key: ""  # ユーザーが設定
    use_websocket: true  # WebSocket使用（高速化）
    models:
      youtube_impact: "civitai:25694@143906"      # インパクト型サムネイル
      youtube_curiosity: "civitai:4384@128713"    # 好奇心型サムネイル
      youtube_authority: "civitai:133005@148204"  # 権威型サムネイル
      blog_featured: "civitai:25694@143906"       # ブログアイキャッチ
      blog_section: "civitai:4201@130072"         # ブログセクション画像
    
    # 生成設定
    generation:
      steps: 25
      cfg_scale: 7.0
      negative_prompt: "blurry, low quality, text, watermark, signature, distorted, ugly"
  
  # Stable Diffusion設定（フォールバック）
  stable_diffusion:
    provider: replicate  # replicate, huggingface, local
    api_settings:
      replicate:
        api_token: ""
        model: "stability-ai/stable-diffusion:27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478"
      huggingface:
        api_token: ""
        model: "stabilityai/stable-diffusion-2-1"
      local:
        server_url: "http://localhost:7860"
        model_path: ""
  
  # 画像最適化設定
  image_optimization:
    # YouTubeサムネイル再利用設定
    reuse_youtube_for_blog: true  # YouTubeサムネイルをブログアイキャッチに再利用
    
    # ブログ画像設定
    blog_images:
      featured_image:
        width: 1200
        height: 630   # OGP最適化
        source: "youtube_reuse"  # youtube_reuse or generate_new
      
      section_images:
        count: 2      # セクションあたり最大2枚
        width: 800
        height: 450
        placement: "after_h2"  # H2タグの直後に配置
    
    # 品質設定
    quality:
      format: "PNG"
      compression: 85
      optimize: true
  
# テンプレート設定
templates:
  blog: templates/blog_post.j2
  youtube: templates/youtube_description.j2
  twitter: templates/twitter_post.j2
  
# ソーシャルメディア設定
social_media:
  # X (Twitter) 投稿設定
  x:
    max_length: 140            # 日本語文字数制限
    thread_mode: true          # スレッド投稿対応
    include_link: true         # ブログリンク含む
    hashtag_strategy: smart    # スマートハッシュタグ選択
    auto_post: false           # 自動投稿（false=手動コピペ）
    
  # スケジューラー設定
  schedule_file: social_schedule.json
  
# 内部リンク設定
internal_linking:
  posts_directory: _posts
  link_database: internal_links.json
  similarity_threshold: 0.6    # 関連記事判定閾値
  max_related_posts: 3         # 最大関連記事数
  enable_backlinks: true       # 逆リンク機能
  update_existing_posts: true  # 既存記事の更新

# 処理設定
processing:
  parallel_jobs: 2
  chunk_size: 30               # 30秒ごとに処理（大きな動画用）
  auto_cleanup: true           # 一時ファイル自動削除